/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programm;

import java.util.Collection;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.animation.KeyValue;
import javafx.beans.binding.Bindings;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import klassen.Gaesteliste;
import klassen.Gast;
import klassen.GastExceptions;

/**
 *
 * @author Markus
 */
public class GaestelisteDialog extends javax.swing.JFrame {

    /**
     * Creates new form GaestelisteDialog
     */
    public GaestelisteDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonEinladen = new javax.swing.JButton();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldAnzahl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEinladungen = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSummeEinladung = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAnzahlGaesteZusage = new javax.swing.JTextField();
        jButtonAntwort = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldSummeZugesagt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaGaeste = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Gästeliste Geburtstagsparty");

        jLabel2.setText("Name: ");

        jLabel3.setText("Anzahl:");

        jButtonEinladen.setText("Einladen");
        jButtonEinladen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEinladenActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListEinladungen);

        jLabel4.setText("Summe Eingeladene:");

        jTextFieldSummeEinladung.setEnabled(false);
        jTextFieldSummeEinladung.setKeymap(null);

        jLabel5.setText("Anzahl:");

        jButtonAntwort.setText("Antwort");
        jButtonAntwort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAntwortActionPerformed(evt);
            }
        });

        jLabel6.setText("Summe Zugesagt:");

        jTextFieldSummeZugesagt.setEnabled(false);
        jTextFieldSummeZugesagt.setKeymap(null);

        jTextAreaGaeste.setColumns(20);
        jTextAreaGaeste.setRows(5);
        jScrollPane2.setViewportView(jTextAreaGaeste);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAnzahl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEinladen)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldAnzahlGaesteZusage, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonAntwort, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSummeEinladung, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSummeZugesagt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnzahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEinladen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSummeEinladung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldSummeZugesagt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAnzahlGaesteZusage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAntwort))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static int gaesteEingeladenGesamt = 0;
    static int gaesteZugesagtGesamt = 0;


    private void jButtonEinladenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEinladenActionPerformed
        try {Integer.valueOf(jTextFieldAnzahl.getText());}
        catch (NumberFormatException ex){
            
            JOptionPane.showMessageDialog(rootPane, "Bitte erfassen Sie im Feld Anzahl ausschließlich Zahlen.");
        } 

            String name = jTextFieldName.getText();
            int anzahl = Integer.valueOf(jTextFieldAnzahl.getText());

            Gast gast;
            try {
                gast = new Gast(name, anzahl);
                eingeladen.add(gast);
                gaesteEingeladenGesamt += anzahl;
                Collections.sort(eingeladen);
                aktualisiereAnzeige();

            } catch (GastExceptions ex) {
                JOptionPane.showMessageDialog(rootPane, ex);

            }
        
    }//GEN-LAST:event_jButtonEinladenActionPerformed

    private void jButtonAntwortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAntwortActionPerformed
        if (eingeladen.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "noch keine Gäste eingeladen.");
        } else {

            if (jTextFieldAnzahlGaesteZusage.getText() == null) {

                JOptionPane.showMessageDialog(rootPane, "Bitte erfassen Sie die Anzahl der Zusagen.");
            } else {
                if (jListEinladungen.getSelectedIndex() < 0) {
                    JOptionPane.showMessageDialog(rootPane, "Bitte wählen Sie den Gast aus, der zugesagt hat.");
                } else {
                    try {
                        int auswahl = jListEinladungen.getSelectedIndex();
                        int anzahl = Integer.valueOf(jTextFieldAnzahlGaesteZusage.getText());

                        String name = eingeladen.get(auswahl).getName();
                        Gast gast = new Gast(name, anzahl);

                        zugesagt.add(gast);
                        eingeladen.remove(auswahl);
                        Collections.sort(zugesagt);
                        gaesteZugesagtGesamt += anzahl;
                        aktualisiereAnzeige();
                    } catch (GastExceptions ex) {
                        JOptionPane.showMessageDialog(rootPane, ex);
                    }

                }
            }
        }

    }//GEN-LAST:event_jButtonAntwortActionPerformed
    public void aktualisiereAnzeige() {
        jTextFieldSummeEinladung.setText(String.valueOf(gaesteEingeladenGesamt));
        jTextFieldSummeZugesagt.setText(String.valueOf(gaesteZugesagtGesamt));
        DefaultComboBoxModel model = new DefaultComboBoxModel(eingeladen.toArray());
        jListEinladungen.setModel(model);

        jTextAreaGaeste.setText(zugesagt.toString());

        jTextFieldName.setText("");
        jTextFieldAnzahl.setText("");
        jTextFieldAnzahlGaesteZusage.setText("");
        
        jTextFieldName.grabFocus();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GaestelisteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GaestelisteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GaestelisteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GaestelisteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GaestelisteDialog().setVisible(true);
            }
        });
    }
    private Gaesteliste eingeladen = new Gaesteliste();
    private Gaesteliste zugesagt = new Gaesteliste();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAntwort;
    private javax.swing.JButton jButtonEinladen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListEinladungen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaGaeste;
    private javax.swing.JTextField jTextFieldAnzahl;
    private javax.swing.JTextField jTextFieldAnzahlGaesteZusage;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSummeEinladung;
    private javax.swing.JTextField jTextFieldSummeZugesagt;
    // End of variables declaration//GEN-END:variables
}
